name: flutter_timer_app
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:

  shared_preferences: ^2.5.3
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1  
  cupertino_icons: ^1.0.8
  drift: ^2.28.2
  drift_flutter: ^0.2.7
  path_provider: ^2.1.5
  sqflite: ^2.4.1
  path: ^1.9.0
  equatable: ^2.0.7
  get_it: ^8.2.0
  provider: ^6.1.5
  uuid: ^4.5.1
  modal_bottom_sheet: ^3.0.0
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^4.0.1
  stop_watch_timer: ^3.2.2
  rxdart: ^0.28.0
  json_annotation: ^4.6.0
  sliver_tools: ^0.2.12
  audioplayers: ^6.5.1
  go_router: ^16.2.4
  intl: ^0.20.2

dev_dependencies:
  drift_dev: ^2.28.3
  build_runner: ^2.7.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.11.0
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/mp3s/
  uses-material-design: true
